#!/bin/bash
# From GersonFeDutra

# log="/tmp/#0bca6a-log.md"

#for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
#for line in "$@"; do
echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | while read file
do
	
	#echo "$file" >> $log
	#xdg-open $log

	#base=$path

	#dir="$file"
	dir=$file
	
	if [ -f "$dir" ];then
		# Is File
		file="$(basename "${dir}")"
		path="$(dirname "${dir}")"
		if [[ "${file#*.}" == "exe" ]];then
				guake --show -n "$path" -r "$path" -t -e "wine \"$dir\""
		fi
	# elif [ -d "$dir" ]; then
	# Is Directory
		# guake --show -n "$dir" -r "$dir" -t
	fi
done
